# Starting with sample from VITE docs, see https://vite.dev/guide/static-deploy#github-pages
name: Deploy Vite app to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Set the permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Concurrency rules: allow only one deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      APP_DIR: website
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Populate .env
        run: |
          echo "VITE_BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "${{ env.APP_DIR }}/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ env.APP_DIR }}/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
